### ISSUE TITLE
Car leaves the lane when I switch on the "Camera" button in the Simulator

### ISSUE THREAD

**Issue by Harry79** [udacity/CarND-Capstone#136]
The v1.3 release of the simulator solved a serious issue which prevented me from running the project on my machine.

The issue I had is that the car left the track suddenly after following the central lane for some time. The issue is completely solved with the v1.3 simulator when turning off the camera. When turning on the camera the issue is present as it was with the v1.2 simulator.

My first setup was running the simulator on Windows and ROS in a VirtualBox. I also tried native Slackware. The issue was the same.

Please, solve the camera issue.

**Comment by macd** [comment]
look at the comments in #1217 https://github.com/udacity/sdc-issue-reports/issues/1217 and see if the setup I mention last can help you.

**Comment by Harry79** [comment]
@macd, it does help somewhat.
The first time I tried with the camera on right from the beginning, the car only moved with 2 mps. So I gave it another try.
The second time I tried with camera off and turned it on when the car got to 25 mps. The car still left the track after some time.

Are the sources of the simulator available?

**Comment by Harry79** [comment]
Changed my network adapter in VirtualBox to PCnet-FAST III. Now the car is not leaving the track. It is still far from driving in the middle of the lane, the frame rate is very very low at some places on the track but at least it does not leave the track.

**Comment by macd** [comment]
@Harry79, well that sounds like progress!

I think Udacity should change the simulator so that it publishes the
traffic light
info even when the camera is turned off.  That way the control stack can be
completely developed independently from the TL detection code.

You can do a fair amount of development with the camera turned off.  You can
see how the car accelerates from a stop, how the yaw angle controller works
at a (somewhat) constant speed, and how the throttle controller keeps the
speed
close to the target speed.

What is missing then is how the steering control acts while breaking.  You
can
(somewhat) see how that works at the first few traffic lights, but as you
found
out, it will be hard to debug any subtle issues between braking and steering
control if the steering angle isn't always correct.

**Comment by mvirgo** [comment]
We've now moved the project into a classroom workspace to help remove this as an issue; no further responses in ~6 months, but please open a new issue if anyone sees the same behavior within the workspace!

**Comment by Harry79** [comment]
I upgraded my PC from an i5-750 to an i5-8600K, the issue was gone.
