### ISSUE TITLE
Focal lengths wrong

### ISSUE THREAD

**Issue by friedricherbs** [udacity/CarND-Capstone#20]
Hi,

from sim_traffic_light_config.yaml:

"focal_length_x: 0.97428
focal_length_y: 1.73205"

I think these values are probably not correct. In 10m distance, an object with a width oft 1m (wider than a traffic light) would just be 0.1 pixels wide in the image plane which is impossible to detect of course. Typical values for fx and fy are in the range of 1000 pixels. As a consequence, the projection of the TLs always ends up at the focus of expansion. Please clarify or adapt focal length values.

**Comment by ckirksey3** [comment]
@awbrown90 could you look into this?

**Comment by friedricherbs** [comment]
Any update here?

**Comment by ChrisShepherd81** [comment]
Is there any update? This is an blocking issue.

**Comment by ckirksey3** [comment]
Sorry for the slow response here. Since we don't have a way to provide a representation of focal length in Unity (see @awbrown90's [response in the forums](https://discussions.udacity.com/t/focal-length-wrong/358568/19)), we've decided to focus on supporting the approach of classifying the entire image as either containing a red, yellow, or green light. I've removed these mislead focal length numbers from the repo (https://github.com/udacity/CarND-Capstone/pull/79)
